---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "Breaking"
    lables:
      - "major"
      - "breaking"
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Documentation"
    labels:
      - "documentation"
  - title: "Workflows"
    labels:
      - "workflow"
version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "bug"
      - "fix"
  default: patch
change-template: "- $TITLE, by @$AUTHOR (#$NUMBER)"
template: |
  # Changes

  $CHANGES
