---
- name: restart cilium
  ansible.builtin.shell: |
    {{ cilium_kubectl_bin_path }} -n kube-system rollout restart deployment/cilium-operator
    {{ cilium_kubectl_bin_path }} -n kube-system rollout restart daemonset/cilium
  environment:
    KUBECONFIG: "{{ cilium_kubeconfig_path }}"

- name: wait for cilium to be running and ready 2
  ansible.builtin.shell:
    cmd: "{{ cilium_cli_bin_path }} status --wait --wait-duration 5m"
  environment:
    KUBECONFIG: "{{ cilium_kubeconfig_path }}"
