---
name: CI

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]


jobs:
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Setup Python 3
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip3 install yamllint

      - name: Lint code
        run: yamllint .

  ansiblelint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "--profile production"
          setup_python: "true"
          requirements_file: "./requirements.yml"
