---
name: Release to Ansible Galaxy

on:
  release:
    types: [published]

jobs:
  release:
    name: Ansible Galaxy Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Setup Python 3
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
